# Generated by Django 4.1 on 2022-08-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontime',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questiontime',
            name='test',
        ),
        migrations.RemoveField(
            model_name='questiontime',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='group_rating',
            field=models.IntegerField(default=0, verbose_name='Место в группе'),
        ),
        migrations.DeleteModel(
            name='QuestionScore',
        ),
        migrations.DeleteModel(
            name='QuestionTime',
        ),
    ]
